version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"

  - package-ecosystem: "gradle"
    directory: "/backend/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"

#  - package-ecosystem: "npm"
#    directory: "/frontend/"
#    patterns: ["*"]
#    multi-ecosystem-group: "dependencies"
#
#  - package-ecosystem: "npm"
#    directory: "/infrastructure/"
#    patterns: ["*"]
#    multi-ecosystem-group: "dependencies"
